# This is a basic workflow to help you get started with Actions

name: codecov-coverage

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  on:
    schedule:
      - cron: "*/1 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: codecov
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@239febf655bba88b16ff5dea1d3135ea8663a1f9
        uses: codecov/codecov-action@v1.0.15
        with:
          # User defined upload name. Visible in Codecov UI
          name: seogi
        env:
          CODECOV_TOKEN: 12bc5c26-ecec-4fee-aebe-c9907ce87048
      # Runs a set of commands using the runners shell
      - name: Write log
        run: |
          echo Succeed your project coverage
